provenance:
  _type: https://in-toto.io/Statement/v1
  predicateType: https://slsa.dev/provenance/v1
  subject:
  - name: skills/BuildSkill/UserConfigSchema.md
    digest:
      sha256: 6d5ebfd44d4a51b167af0550bdefbae3b7c6108699f2d4a93225bdde5ce1f45e
  predicate:
    buildDefinition:
      buildType: adopt/v1
      externalParameters:
        source: ''
        upstream_url: https://github.com/N4M3Z/forge-core
        upstream_commit: ''
        transforms_applied:
        - copy
      resolvedDependencies:
      - name: upstream
        uri: https://github.com/N4M3Z/forge-core
        digest:
          sha256: 092323fe9007adf05a4434b9b730d37038014134c528d25705d63b8d55348ee8
    runDetails:
      builder:
        id: rune-cli
        version:
          rune: 0.5.0
      metadata:
        startedOn: 2026-07-18T19:16:19.868199+00:00
        review: reviewed
