provenance:
  _type: https://in-toto.io/Statement/v1
  predicateType: https://slsa.dev/provenance/v1
  subject:
  - name: skills/SimplifiedTechnicalEnglish/config/lint-rules.json
    digest:
      sha256: 0cb412d1c2d0efa60c9fcd8ea6fd6285f7272d9e5d2dffc8b13b269c0268ebc9
  predicate:
    buildDefinition:
      buildType: adopt/v1
      externalParameters:
        source: ''
        upstream_url: https://github.com/danyuchn/asd-ste100-skill/tree/d5ce157 + https://github.com/woosal1337/blog/tree/51100c9/videos/ep01-the-cure-for-ai-slop
        upstream_commit: ''
        transforms_applied:
        - extract policy lists from ste-lint.py
      resolvedDependencies:
      - name: upstream
        uri: https://github.com/danyuchn/asd-ste100-skill/tree/d5ce157 + https://github.com/woosal1337/blog/tree/51100c9/videos/ep01-the-cure-for-ai-slop
        digest:
          sha256: bedba551157b7cf6378ecf97d29e6606496c49a8df83d7778e5f330e48c9595e
    runDetails:
      builder:
        id: rune-cli
        version:
          rune: 0.5.0
      metadata:
        startedOn: 2026-08-13T12:26:06.828768+00:00
        review: reviewed
