provenance:
  _type: https://in-toto.io/Statement/v1
  predicateType: https://slsa.dev/provenance/v1
  subject:
  - name: skills/.mdschema
    digest:
      sha256: 07b32cacbaa15d9dedb7e59f242565837e4bc971587a3254c472a3c30f12ce53
  predicate:
    buildDefinition:
      buildType: https://github.com/runedeck/cli/init/v1
      externalParameters:
        source: https://github.com/runedeck/cli
      resolvedDependencies:
      - uri: templates/init/skills/.mdschema
        digest:
          sha256: 0eea82aa518184d54cc9466c0061d21b272a491d5839a863efbe4960fbf2ffeb
    runDetails:
      builder:
        id: https://github.com/runedeck/cli
        version:
          rune: 0.5.0
      metadata:
        startedOn: 2026-09-15T14:36:17.047475+00:00
